version: '2'
services:
    app:
        restart: always
        ports:
            - 80:80
        image: app:app
        build: .
        volumes:
            - /var/log/app
            - ./:/app
        command: "start"
